---
- name: login2 to bastion
  hosts: all
  tasks:
    - name: echo test
      shell: |
        ssh kwang@10.130.206.5 echo test
      delegate_to: my_local
      vars:
        ansible_ssh_pass: "rhkd3695"
