---
- name: get master
  hosts: all
  tasks:
    - name: test no rest api master get
      debug:
        var: hostvars[delegate_host].command_output.stdout
      vars:
        delegate_host: "{{ inventory_hostname }}"
