---
- name: create ssh key
  hosts: all
  tasks:
    - name: check ssh key
      command: ls | grep id_rsa.pub
      args:
        chdir: "/Users/kwang/.ssh/"
      register: check_pub_key

    - name: create ssh key
      command: ssh-keygen -t rsa -f "{{ssh_key_path}}" -N ""
      vars:
        ssh_key_path: "/Users/kwang/.ssh/id_rsa"
      ignore_errors: yes
      when: check_pub_key is defined and check_pub_key != ""

    - name: get id_rsa public key
      shell: echo `cat id_rsa.pub`
      args:
        chdir: "/Users/kwang/.ssh"
      register: public_key

    - name: print public key
      debug:
        msg:
          - "public_key : {{ public_key.stdout }}"
