---
- name: create ssh key
  hosts: all
  tasks:
    - name: check if ssh key exists
      stat:
        path: "/Users/kwang/.ssh/id_rsa.pub"
      register: ssh_key_exists

    - name: create ssh key if it doesn't exist
      command: ssh-keygen -t rsa -f "/Users/kwang/.ssh/id_rsa" -N ""
      when: not ssh_key_exists.stat.exists

    - name: get id_rsa public key
      shell: echo `cat id_rsa.pub`
      args:
        chdir: "/Users/kwang/.ssh"
      register: public_key

    - name: print public key
      debug:
        msg:
          - "public_key : {{ public_key.stdout }}"
