---
- name: post to master
  hosts: all
  tasks:
    - name: Make a POST request
      uri:
        url: "http://localhost:8013/api/v2/analytics/reports/"
        method: POST
        headers:
          Content-Type: application/json
          Authorization: "Token VUontBDk1QF0HxMylXIn2aJRtScjrg"
        body_format: json
        body:
          name: "My Test Report"
          type: "execution"
      register: result

    - name: Print result
      debug:
        var: result
