---
- name: post to master
  hosts: all
  tasks:
    - name: test no rest api
      shell: |
        ls | grep framework | awk -F 'moreh-' '{print $2}' | awk -F '-Linux*' '{print $1}'
      register: command_output
      delegate_to: office-mac
