---
- name: test
  hosts: all
  tasks:
    - name: echo test
      set_fact: |
        test_var: "Hello, world"

    - name: rest api test
      shell: |
        curl --silent --insecure --user "moreh:Framework4AI!" --location --request POST --header 'Content-Type: application/json' "http://localhost:8013/api/v2/job_templates/10/launch/" --data @<(cat <<EOF { "extra_vars": { "ENABLED_VERSION": "def" } } EOF)
