---
- name: test
  hosts: all
  tasks:
    - name: echo test
      uri:
        url: "http://localhost:8013/api/v2/hosts/"
        method: POST
        status_code: 201
        headers:
          Content-Type: application/json
        body_format: json
        body:
          name: "home-mac"
          inventory: 2
          enabled: true
        force_basic_auth: yes
        user: "moreh"
        password: "{{ PASSWORD }}"
        validate_certs: false
      register: response_result

    - name: print
      debug:
        var: response_result
