---
- name: test2
  hosts: all
  tasks:
    - name: get necessary version list
      shell:
        cmd: |
          echo {{ TEST_VAR1 }}
      executable: /bin/bash
      register: test

    - name: print test
      debug:
        var: test
