---
- name: test3
  hosts: all
  tasks:
    - name: variable test
      shell: |
        echo `ls $HOME | grep ff`
      register: test_var

    - name: print
      debug:
        msg:
          - "test : {{ test_var }}"
      when: test_var.stdout is defined and test_var.stdout != ""
