---
- name: test2
  hosts: all
  tasks:
  - name: create file
    file:
      path: "/Users/kwang/test/blockinfile"
      state: touch

  - name: blockinfile test
    blockinfile:
      path: "/Users/kwang/test/blockinfile"
      insertafter: EOF
      block: |
        testtesttest{{item.0}}
    with_indexed_items:
      - 1
      - 2
      - 3
