---
- name: test3
  hosts: all
  tasks:
    - name: variable test
      shell: |
        echo "{{ item }}cde"
    - name: variable test2
      shell: |
        echo "{{ item }}fgh"
  with_items:
    - "{{ TEST_VAR_LIST.split() }}"
