---
- name: test
  hosts: all
  tasks:
    - name: echo test
      shell: |
        echo "Hello, world"
      register: result

    - name: set variable
      awx_artifacts:
        name: result
        content: "{{ result.stdout }}"
