---
- name: Change Infiniband Subnet
  hosts: all
  tasks:
    - name: "delete netplan infiniband yaml"
      file:
        path: "/Users/kwang/test/netplan/infiniband.yaml"
        state: absent

    - name: "touch netplan infiniband yaml"
      file:
        path: "/Users/kwang/test/netplan/infiniband.yaml"
        state: touch

    - name: ib ip setup-1
      blockinfile:
        path: /Users/kwang/test/netplan/inifiniband.yaml
        insertafter: EOF
        block: |
          network:
            ethernets:

    - name: ib ip setup-2
      blockinfile:
        path: /Users/kwang/test/netplan/inifiniband.yaml
        insertafter: EOF
        marker: "# {mark} ib{{item.0}} INSERTION"
        block: |
          # ib {{item.0}}
              ib{{item.0}}:
                addresses:
                - 192.168.temp.temp
                dhcp4: false
      with_indexed_items:
        - 1
        - 2
        - 3

    - name: ib ip setup-3
      blockinfile:
        path: /Users/kwang/test/netplan/inifiniband.yaml
        insertafter: EOF
        marker: "# {mark} INSERTION END"
        block: |
          # insert version
            version: 2
