---
- name: Change Infiniband Subnet
  hosts: all
  tasks:
  - name: "get device index"
    shell: echo `hostname` | grep -o '[1-9][0-9]*$'
    register: device_id
  - name: "delete netplan infiniband yaml"
    file:
      path: "/Users/kwang/test/netplan/infiniband.yaml"
      state: absent
  - name: "touch netplan infiniband yaml"
    file:
      path: "/Users/kwang/test/netplan/infiniband.yaml"
      state: touch
  - name: "write netplan infiniband yaml"
    blockinfile:
      path: "/Users/kwang/test/netplan/infiniband.yaml"
      insertafter: EOF
      block: |
        network:
          ethernets:
            ib0:
              addresses:
              - 192.168.110.{{ device_id.stdout }}/18
              dhcp4: false
            ib1:
              addresses:
              - 192.168.111.{{ device_id.stdout }}/18
              dhcp4: false
  - name: "write netplan infiniband yaml2"
    blockinfile:
      path: "/Users/kwang/test/netplan/infiniband.yaml"
      insertafter: EOF
      block: |
          version: 2
