---
- name: test2
  hosts: all
  tasks:
    - name: blockinfile test
      blockinfile:
        path: /Users/kwang/test
        insertafter: EOF
        block: |
          testtesttest
      with_items:
        - 1
        - 2
        - 3
