---
- name: test2
  hosts: all
  tasks:
    - name: set command
      set_fact:
        command_to_test: >-
          {% if TT == 'a' %}
            echo 'aaaaa'
          {% elif TT == 'b' %}
            echo 'bbbbb'
          {% else %}
            echo 'ccccc'
          {% endif %}

    - name: test
      shell: |
        {{ command_to_test }}
