---
- name: test2
  hosts: all
  tasks:
    - name: get host test
      uri:
        url: "http://localhost:8013/api/v2/hosts/"
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
        body_format: json
        force_basic_auth: yes
        user: "moreh"
        password: "{{ PASSWORD }}"
        validate_certs: false
        return_content: no
      register: host_info_tmp1

    - name: Parse Link header
      set_fact:
        total_pages: "{{ host_info_tmp1.json | regex_findall('page=(\\d+)') | map('int') | max }}"

    - name: get host test
      uri:
        url: "http://localhost:8013/api/v2/hosts/?page={{ item }}"
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
        body_format: json
        force_basic_auth: yes
        user: "moreh"
        password: "{{ PASSWORD }}"
        validate_certs: false
        return_content: yes
      register: host_info_tmp2
      loop: "{{ range(1, total_pages | int + 1) | list }}"

    - name: print test
      debug:
        var: item.json
      loop: "{{ host_info_tmp2 }}"
