---
- name: test
  hosts: all
  tasks:
    - name: echo test
      uri:
        url: "http://localhost:8013/api/v2/job_templates/10/launch/"
        method: POST
        status_code: 201
        headers:
          Content-Type: application/json
        body_format: json
        body:
          extra_vars:
            TEST_VAR1: "abcdefg"
        force_basic_auth: yes
        user: "moreh"
        password: "{{ PASSWORD }}"
        validate_certs: false
