---
- name: Example Playbook
  hosts: all
  tasks:
    - name: get job stdout
      shell: echo "0 1 2 3 4"
      register: test_stdout

    - name: register list
      set_fact:
        test_list: "{{ test_stdout.stdout.split() }}"

    - name: test print
      command: echo {{ ansible_loop.index0 }}
      with_items:
        - "{{ test_list }}"
